from djitellopy import Tello
import time

tello = Tello()
tello.connect()

response = tello.get_battery()
print("Battery % :", response)

time.sleep(5)

for x in range(2):
    print("Drone Start : ")
    tello.takeoff()
    print("Wait 2sec")
    #time.sleep(2)
    tello.move_up(80)
    #print("Wait 2sec")
    #time.sleep(2)
    tello.move_forward(100)
    print("Wait 2sec")
    #time.sleep(2)
    # tello.rotate_counter_clockwise(90)
    # print("Wait 2sec")
    # time.sleep(2)
    # tello.move_forward(100)
    # print("Wait 2sec")
    # time.sleep(2)
    # tello.rotate_counter_clockwise(90)
    # print("Wait 2sec")
    # time.sleep(2)
    # tello.move_forward(100)
    # tello.rotate_counter_clockwise(90)
    # print("Wait 2sec")
    # time.sleep(2)
    # tello.move_forward(100)
    # time.sleep(2)
    tello.move_left(100)
    #time.sleep(2)
    tello.move_back(100)
    #time.sleep(2)
    tello.move_right(100)
    #time.sleep(2)
    tello.move_forward(100)
    #time.sleep(2)
    tello.land()
    print("Land !!!!")
    time.sleep(5)
